# Generated by Django 4.2.19 on 2025-02-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('openingDate', models.DateField()),
                ('requiredExperience', models.IntegerField(max_length=50)),
                ('condition', models.TextField()),
            ],
            options={
                'db_table': 'sos_position',
            },
        ),
    ]
