# Generated by Django 4.2.19 on 2025-02-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_position_requiredexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='identifier',
        ),
    ]
