# Generated by Django 4.2.19 on 2025-03-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='fistName',
            new_name='firstName',
        ),
    ]
