# Generated by Django 4.2.19 on 2025-03-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_fistname_test_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('addedDate', models.DateField()),
            ],
            options={
                'db_table': 'sos_favoritelist',
            },
        ),
    ]
