# Generated by Django 4.2.19 on 2025-03-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_fistname_test_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(default='', max_length=50)),
                ('birthDate', models.DateField(max_length=20)),
                ('contactNumber', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'sos_employee',
            },
        ),
    ]
